### ISSUE TITLE
RouteEnhancer does not work for path_segment but uid and sku?

### ISSUE THREAD

**Issue by j4k3** [extcode/cart#326]
## Bug Report

**Current Behavior**
I've written a routeEnhancer configuration for a tx_cart installation, but I can't get it to work properly. The urls are generated correcly but upon opening the links, I get redirected to the 404 error page. No error is logged. However, if I switch to either uid or sku for routeFieldName, everything works perfectly. I've now made a copy of the sku sow and set it as path_segment, making sure variable type as well as data are the same for sku and path_segment, but the error persists. I can use sku for route generation, but as soon as I switch over to path_segment, the links no longer work.

I've never experienced anything like this with RouteEnhancers, has anyone else? Can anybody tell me whats going on here?

Heres the snippet of my SiteConfiguration.php

      -
        type: Extbase
        extension: Cartproducts
        plugin: Products
        routes:
          -
            routePath: '/artikel-{product_slug}'
            _controller: 'Product::show'
            _arguments:
              product_slug: product
        defaultController: 'Product::list'
        aspects:
          product_slug:
            type: PersistedAliasMapper
            tableName: tx_cartproducts_domain_model_product_product
            routeFieldName: path_segment

**Expected behavior/output**
Work.

**Environment**
- TYPO3 version(s): 9.5.24
- cart version: 2.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by extcode** [comment]
Can you edit your Configuration so it is readable?

Our configuration looks like this:
```
routeEnhancers:
    CartProducts:
        type: Extbase
        extension: CartProducts
        plugin: Products
        routes:
        - { routePath: '/{product_title}', _controller: 'Product::show', _arguments: {'product_title': 'product'} }
        defaultController: 'Product::show'
        aspects:
            product_title:
                type: PersistedAliasMapper
                tableName: 'tx_cartproducts_domain_model_product_product'
                routeFieldName: 'path_segment'
```
